Get devices for measurement successfully!
No: 1	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(TVMError("[13:47:58] /homes/zheng321/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'i.inner.init'  'j.inner.init'  does not appeared in api_args\n\nStack trace returned 10 entries:\n[bt] (0) /homes/zheng321/tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x1b0) [0x7f88872d5210]\n[bt] (1) /homes/zheng321/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x39) [0x7f88872d5e39]\n[bt] (2) /homes/zheng321/tvm/build/libtvm.so(tvm::ir::MakeAPI(HalideIR::Internal::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)+0x331b) [0x7f88874fa70b]\n[bt] (3) /homes/zheng321/tvm/build/libtvm.so(+0x7e70ba) [0x7f888730e0ba]\n[bt] (4) /homes/zheng321/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7f88878af4de]\n[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f888bfdcdae]\n[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7f888bfdc71f]\n[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2b4) [0x7f888c221ba4]\n[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12223) [0x7f888c222223]\n[bt] (9) python3(_PyObject_FastCallKeywords+0x19c) [0x59f9fc]\n\n",),), error_no=2, all_cost=0.016196250915527344, timestamp=1543862878.6742332)	[('tile_y', [128, 4]), ('tile_x', [256, 2])],,None,12
BEST_FLOPS 0.0000000000
No: 2	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(TVMError("[13:47:58] /homes/zheng321/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'i.inner.init'  'j.inner.init'  does not appeared in api_args\n\nStack trace returned 10 entries:\n[bt] (0) /homes/zheng321/tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x1b0) [0x7f88872d5210]\n[bt] (1) /homes/zheng321/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x39) [0x7f88872d5e39]\n[bt] (2) /homes/zheng321/tvm/build/libtvm.so(tvm::ir::MakeAPI(HalideIR::Internal::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)+0x331b) [0x7f88874fa70b]\n[bt] (3) /homes/zheng321/tvm/build/libtvm.so(+0x7e70ba) [0x7f888730e0ba]\n[bt] (4) /homes/zheng321/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7f88878af4de]\n[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f888bfdcdae]\n[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7f888bfdc71f]\n[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2b4) [0x7f888c221ba4]\n[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12223) [0x7f888c222223]\n[bt] (9) python3(_PyObject_FastCallKeywords+0x19c) [0x59f9fc]\n\n",),), error_no=2, all_cost=0.016535520553588867, timestamp=1543862878.674356)	[('tile_y', [16, 32]), ('tile_x', [64, 8])],,None,35
BEST_FLOPS 0.0000000000
No: 3	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(TVMError("[13:47:58] /homes/zheng321/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'i.inner.init'  'j.inner.init'  does not appeared in api_args\n\nStack trace returned 10 entries:\n[bt] (0) /homes/zheng321/tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x1b0) [0x7f88872d5210]\n[bt] (1) /homes/zheng321/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x39) [0x7f88872d5e39]\n[bt] (2) /homes/zheng321/tvm/build/libtvm.so(tvm::ir::MakeAPI(HalideIR::Internal::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)+0x331b) [0x7f88874fa70b]\n[bt] (3) /homes/zheng321/tvm/build/libtvm.so(+0x7e70ba) [0x7f888730e0ba]\n[bt] (4) /homes/zheng321/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7f88878af4de]\n[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f888bfdcdae]\n[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7f888bfdc71f]\n[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2b4) [0x7f888c221ba4]\n[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12223) [0x7f888c222223]\n[bt] (9) python3(_PyObject_FastCallKeywords+0x19c) [0x59f9fc]\n\n",),), error_no=2, all_cost=0.017359256744384766, timestamp=1543862878.6744323)	[('tile_y', [64, 8]), ('tile_x', [16, 32])],,None,53
BEST_FLOPS 0.0000000000
No: 4	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(InstantiationError('Skipped because of invalid gpu kernel',),), error_no=1, all_cost=0.014210700988769531, timestamp=1543862878.674527)	[('tile_y', [16, 32]), ('tile_x', [1, 512])],,None,95
BEST_FLOPS 0.0000000000
No: 5	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(TVMError("[13:47:58] /homes/zheng321/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'i.inner.init'  'j.inner.init'  does not appeared in api_args\n\nStack trace returned 10 entries:\n[bt] (0) /homes/zheng321/tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x1b0) [0x7f88872d5210]\n[bt] (1) /homes/zheng321/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x39) [0x7f88872d5e39]\n[bt] (2) /homes/zheng321/tvm/build/libtvm.so(tvm::ir::MakeAPI(HalideIR::Internal::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)+0x331b) [0x7f88874fa70b]\n[bt] (3) /homes/zheng321/tvm/build/libtvm.so(+0x7e70ba) [0x7f888730e0ba]\n[bt] (4) /homes/zheng321/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7f88878af4de]\n[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f888bfdcdae]\n[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7f888bfdc71f]\n[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2b4) [0x7f888c221ba4]\n[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12223) [0x7f888c222223]\n[bt] (9) python3(_PyObject_FastCallKeywords+0x19c) [0x59f9fc]\n\n",),), error_no=2, all_cost=0.014758110046386719, timestamp=1543862878.6745863)	[('tile_y', [8, 64]), ('tile_x', [64, 8])],,None,36
BEST_FLOPS 0.0000000000
No: 6	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(TVMError("[13:47:58] /homes/zheng321/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'i.inner.init'  'j.inner.init'  does not appeared in api_args\n\nStack trace returned 10 entries:\n[bt] (0) /homes/zheng321/tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x1b0) [0x7f88872d5210]\n[bt] (1) /homes/zheng321/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x39) [0x7f88872d5e39]\n[bt] (2) /homes/zheng321/tvm/build/libtvm.so(tvm::ir::MakeAPI(HalideIR::Internal::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)+0x331b) [0x7f88874fa70b]\n[bt] (3) /homes/zheng321/tvm/build/libtvm.so(+0x7e70ba) [0x7f888730e0ba]\n[bt] (4) /homes/zheng321/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7f88878af4de]\n[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f888bfdcdae]\n[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7f888bfdc71f]\n[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2b4) [0x7f888c221ba4]\n[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12223) [0x7f888c222223]\n[bt] (9) python3(_PyObject_FastCallKeywords+0x19c) [0x59f9fc]\n\n",),), error_no=2, all_cost=0.015070438385009766, timestamp=1543862878.6746457)	[('tile_y', [64, 8]), ('tile_x', [128, 4])],,None,23
BEST_FLOPS 0.0000000000
No: 7	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(TVMError("[13:47:58] /homes/zheng321/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'j.inner.init'  'i.inner.init'  does not appeared in api_args\n\nStack trace returned 10 entries:\n[bt] (0) /homes/zheng321/tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x1b0) [0x7f88872d5210]\n[bt] (1) /homes/zheng321/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x39) [0x7f88872d5e39]\n[bt] (2) /homes/zheng321/tvm/build/libtvm.so(tvm::ir::MakeAPI(HalideIR::Internal::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)+0x331b) [0x7f88874fa70b]\n[bt] (3) /homes/zheng321/tvm/build/libtvm.so(+0x7e70ba) [0x7f888730e0ba]\n[bt] (4) /homes/zheng321/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7f88878af4de]\n[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f888bfdcdae]\n[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7f888bfdc71f]\n[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2b4) [0x7f888c221ba4]\n[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12223) [0x7f888c222223]\n[bt] (9) python3(_PyObject_FastCallKeywords+0x19c) [0x59f9fc]\n\n",),), error_no=2, all_cost=0.015199661254882812, timestamp=1543862878.6747007)	[('tile_y', [256, 2]), ('tile_x', [64, 8])],,None,31
BEST_FLOPS 0.0000000000
No: 8	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(TVMError("[13:47:58] /homes/zheng321/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'i.inner.init'  does not appeared in api_args\n\nStack trace returned 10 entries:\n[bt] (0) /homes/zheng321/tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x1b0) [0x7f88872d5210]\n[bt] (1) /homes/zheng321/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x39) [0x7f88872d5e39]\n[bt] (2) /homes/zheng321/tvm/build/libtvm.so(tvm::ir::MakeAPI(HalideIR::Internal::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)+0x331b) [0x7f88874fa70b]\n[bt] (3) /homes/zheng321/tvm/build/libtvm.so(+0x7e70ba) [0x7f888730e0ba]\n[bt] (4) /homes/zheng321/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7f88878af4de]\n[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f888bfdcdae]\n[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7f888bfdc71f]\n[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2b4) [0x7f888c221ba4]\n[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12223) [0x7f888c222223]\n[bt] (9) python3(_PyObject_FastCallKeywords+0x19c) [0x59f9fc]\n\n",),), error_no=2, all_cost=0.014591217041015625, timestamp=1543862878.6747575)	[('tile_y', [2, 256]), ('tile_x', [512, 1])],,None,8
BEST_FLOPS 0.0000000000
No: 9	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(InstantiationError('Skipped because of invalid gpu kernel',),), error_no=1, all_cost=0.014893293380737305, timestamp=1543862878.6747978)	[('tile_y', [2, 256]), ('tile_x', [32, 16])],,None,48
BEST_FLOPS 0.0000000000
No: 10	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(InstantiationError('Skipped because of invalid gpu kernel',),), error_no=1, all_cost=0.015149354934692383, timestamp=1543862878.6748755)	[('tile_y', [16, 32]), ('tile_x', [8, 64])],,None,65
BEST_FLOPS 0.0000000000
No: 11	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(TVMError("[13:47:58] /homes/zheng321/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'j.inner.init'  'i.inner.init'  does not appeared in api_args\n\nStack trace returned 10 entries:\n[bt] (0) /homes/zheng321/tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x1b0) [0x7f88872d5210]\n[bt] (1) /homes/zheng321/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x39) [0x7f88872d5e39]\n[bt] (2) /homes/zheng321/tvm/build/libtvm.so(tvm::ir::MakeAPI(HalideIR::Internal::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)+0x331b) [0x7f88874fa70b]\n[bt] (3) /homes/zheng321/tvm/build/libtvm.so(+0x7e70ba) [0x7f888730e0ba]\n[bt] (4) /homes/zheng321/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7f88878af4de]\n[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f888bfdcdae]\n[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7f888bfdc71f]\n[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2b4) [0x7f888c221ba4]\n[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12223) [0x7f888c222223]\n[bt] (9) python3(_PyObject_FastCallKeywords+0x19c) [0x59f9fc]\n\n",),), error_no=2, all_cost=0.017715930938720703, timestamp=1543862878.6869867)	[('tile_y', [256, 2]), ('tile_x', [32, 16])],,None,41
BEST_FLOPS 0.0000000000
No: 12	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(InstantiationError('Skipped because of invalid gpu kernel',),), error_no=1, all_cost=0.014090776443481445, timestamp=1543862878.6870773)	[('tile_y', [1, 512]), ('tile_x', [16, 32])],,None,59
BEST_FLOPS 0.0000000000
No: 13	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(TVMError("[13:47:58] /homes/zheng321/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'j.inner.init'  'i.inner.init'  does not appeared in api_args\n\nStack trace returned 10 entries:\n[bt] (0) /homes/zheng321/tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x1b0) [0x7f88872d5210]\n[bt] (1) /homes/zheng321/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x39) [0x7f88872d5e39]\n[bt] (2) /homes/zheng321/tvm/build/libtvm.so(tvm::ir::MakeAPI(HalideIR::Internal::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)+0x331b) [0x7f88874fa70b]\n[bt] (3) /homes/zheng321/tvm/build/libtvm.so(+0x7e70ba) [0x7f888730e0ba]\n[bt] (4) /homes/zheng321/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7f88878af4de]\n[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f888bfdcdae]\n[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7f888bfdc71f]\n[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2b4) [0x7f888c221ba4]\n[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12223) [0x7f888c222223]\n[bt] (9) python3(_PyObject_FastCallKeywords+0x19c) [0x59f9fc]\n\n",),), error_no=2, all_cost=0.014150619506835938, timestamp=1543862878.6871583)	[('tile_y', [256, 2]), ('tile_x', [8, 64])],,None,61
BEST_FLOPS 0.0000000000
No: 14	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(InstantiationError('Skipped because of invalid gpu kernel',),), error_no=1, all_cost=0.008108139038085938, timestamp=1543862878.6872177)	[('tile_y', [8, 64]), ('tile_x', [1, 512])],,None,96
BEST_FLOPS 0.0000000000
No: 15	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(InstantiationError('Skipped because of invalid gpu kernel',),), error_no=1, all_cost=0.011667490005493164, timestamp=1543862878.6872745)	[('tile_y', [8, 64]), ('tile_x', [8, 64])],,None,66
BEST_FLOPS 0.0000000000
No: 16	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(TVMError("[13:47:58] /homes/zheng321/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'i.inner.init'  does not appeared in api_args\n\nStack trace returned 10 entries:\n[bt] (0) /homes/zheng321/tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x1b0) [0x7f88872d5210]\n[bt] (1) /homes/zheng321/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x39) [0x7f88872d5e39]\n[bt] (2) /homes/zheng321/tvm/build/libtvm.so(tvm::ir::MakeAPI(HalideIR::Internal::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)+0x331b) [0x7f88874fa70b]\n[bt] (3) /homes/zheng321/tvm/build/libtvm.so(+0x7e70ba) [0x7f888730e0ba]\n[bt] (4) /homes/zheng321/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7f88878af4de]\n[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f888bfdcdae]\n[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7f888bfdc71f]\n[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2b4) [0x7f888c221ba4]\n[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12223) [0x7f888c222223]\n[bt] (9) python3(_PyObject_FastCallKeywords+0x19c) [0x59f9fc]\n\n",),), error_no=2, all_cost=0.013742208480834961, timestamp=1543862878.6975825)	[('tile_y', [128, 4]), ('tile_x', [512, 1])],,None,2
BEST_FLOPS 0.0000000000
No: 17	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(TVMError("[13:47:58] /homes/zheng321/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'j.inner.init'  'i.inner.init'  does not appeared in api_args\n\nStack trace returned 10 entries:\n[bt] (0) /homes/zheng321/tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x1b0) [0x7f88872d5210]\n[bt] (1) /homes/zheng321/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x39) [0x7f88872d5e39]\n[bt] (2) /homes/zheng321/tvm/build/libtvm.so(tvm::ir::MakeAPI(HalideIR::Internal::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)+0x331b) [0x7f88874fa70b]\n[bt] (3) /homes/zheng321/tvm/build/libtvm.so(+0x7e70ba) [0x7f888730e0ba]\n[bt] (4) /homes/zheng321/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7f88878af4de]\n[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f888bfdcdae]\n[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7f888bfdc71f]\n[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2b4) [0x7f888c221ba4]\n[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12223) [0x7f888c222223]\n[bt] (9) python3(_PyObject_FastCallKeywords+0x19c) [0x59f9fc]\n\n",),), error_no=2, all_cost=0.015234708786010742, timestamp=1543862878.6976538)	[('tile_y', [2, 256]), ('tile_x', [128, 4])],,None,28
BEST_FLOPS 0.0000000000
No: 18	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(InstantiationError('Skipped because of invalid gpu kernel',),), error_no=1, all_cost=0.013671398162841797, timestamp=1543862878.6977098)	[('tile_y', [4, 128]), ('tile_x', [4, 128])],,None,77
BEST_FLOPS 0.0000000000
No: 19	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(TVMError("[13:47:58] /homes/zheng321/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'j.inner.init'  'i.inner.init'  does not appeared in api_args\n\nStack trace returned 10 entries:\n[bt] (0) /homes/zheng321/tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x1b0) [0x7f88872d5210]\n[bt] (1) /homes/zheng321/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x39) [0x7f88872d5e39]\n[bt] (2) /homes/zheng321/tvm/build/libtvm.so(tvm::ir::MakeAPI(HalideIR::Internal::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)+0x331b) [0x7f88874fa70b]\n[bt] (3) /homes/zheng321/tvm/build/libtvm.so(+0x7e70ba) [0x7f888730e0ba]\n[bt] (4) /homes/zheng321/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7f88878af4de]\n[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f888bfdcdae]\n[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7f888bfdc71f]\n[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2b4) [0x7f888c221ba4]\n[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12223) [0x7f888c222223]\n[bt] (9) python3(_PyObject_FastCallKeywords+0x19c) [0x59f9fc]\n\n",),), error_no=2, all_cost=0.011934280395507812, timestamp=1543862878.7071893)	[('tile_y', [128, 4]), ('tile_x', [128, 4])],,None,22
BEST_FLOPS 0.0000000000
No: 20	GFLOPS: 0.0000/0.0000	cost: 0.0000	result: MeasureResult(costs=(TVMError("[13:47:58] /homes/zheng321/tvm/src/pass/make_api.cc:169: Not all Vars are passed in api_args:  'j.inner.init'  does not appeared in api_args\n\nStack trace returned 10 entries:\n[bt] (0) /homes/zheng321/tvm/build/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x1b0) [0x7f88872d5210]\n[bt] (1) /homes/zheng321/tvm/build/libtvm.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x39) [0x7f88872d5e39]\n[bt] (2) /homes/zheng321/tvm/build/libtvm.so(tvm::ir::MakeAPI(HalideIR::Internal::Stmt, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::Array<tvm::NodeRef, void>, int, bool)+0x331b) [0x7f88874fa70b]\n[bt] (3) /homes/zheng321/tvm/build/libtvm.so(+0x7e70ba) [0x7f888730e0ba]\n[bt] (4) /homes/zheng321/tvm/build/libtvm.so(TVMFuncCall+0x5e) [0x7f88878af4de]\n[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f888bfdcdae]\n[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7f888bfdc71f]\n[bt] (7) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2b4) [0x7f888c221ba4]\n[bt] (8) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12223) [0x7f888c222223]\n[bt] (9) python3(_PyObject_FastCallKeywords+0x19c) [0x59f9fc]\n\n",),), error_no=2, all_cost=0.013641119003295898, timestamp=1543862878.7072587)	[('tile_y', [512, 1]), ('tile_x', [32, 16])],,None,40
BEST_FLOPS 0.0000000000
